### ISSUE TITLE
multiple sites in the same location

### ISSUE THREAD

**Issue by robertjanetzko** [robertjanetzko/LegendsBrowser#28]
it's possible for multiple sites to be in the same location on the world map.

For example, a town, a camp, a road and a bridge can overlap. As a result of it, it's possible for a town to become unclickable and invisible. It just looks like the road, bridge and all, ends in a camp. Even if the town is the capital. :)

**Comment by therahedwig** [comment]
This can be alleviated by using the site rectangle elements (though these are in mid-tile coordinates, that is 16x the world tiles) instead of their direct coordinated. The problem then becomes however that certain sites, like lairs, have absolutely teensy rectangles.

I setup my own world-map lua script to have a minimum of 4x4 for these, and that seems to work fine: http://www.bay12forums.com/smf/index.php?topic=175357.0
